import type { MetadataRoute } from "next";

/**
 * Web app manifest — what makes Chrome offer "Install app" (Android WebAPK,
 * desktop omnibox install) and what iOS reads on Add to Home Screen.
 *
 * Served at `/manifest.webmanifest` by the Next metadata-route convention,
 * which also injects `<link rel="manifest">` into every document. The
 * `.webmanifest` extension is load-bearing: `proxy.ts` skips it in the Clerk
 * matcher, so the file is fetchable anonymously and never bounced to `/login`.
 *
 * No service worker: current Chromium has no service-worker installability
 * check, and `reload-to-update` is the only update path.
 */

/**
 * Permanent app identity. Chrome keys an installed app on `id` (resolved
 * against the origin) — changing it later creates a second app and orphans
 * every existing install. Never a `/n/{id}` path: note ids rotate.
 */
export const PWA_APP_ID = "/";

/** `/` redirects signed-in users to their first note and signed-out to `/login`. */
export const PWA_START_URL = "/";

/** Whole origin: `/login`, `/n/*` and public `/p/*` are one product session. */
export const PWA_SCOPE = "/";

export const PWA_APP_NAME = "agentnote";

/** Dark theme background (`#141414`) — launcher, splash and task-switcher tint. */
export const PWA_THEME_COLOR = "#141414";

/**
 * `any` = the light plate from `favicon.svg` on a dark tile. `maskable` =
 * the same mark kept inside Android's 80% safe zone, fully opaque, so the
 * adaptive-icon mask has nothing transparent to reveal. Generated by
 * `scripts/gen-pwa-icons.mjs`.
 */
export const PWA_ICONS: NonNullable<MetadataRoute.Manifest["icons"]> = [
  { src: "/pwa/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
  { src: "/pwa/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
  {
    src: "/pwa/maskable-192.png",
    sizes: "192x192",
    type: "image/png",
    purpose: "maskable",
  },
  {
    src: "/pwa/maskable-512.png",
    sizes: "512x512",
    type: "image/png",
    purpose: "maskable",
  },
];

export default function manifest(): MetadataRoute.Manifest {
  return {
    id: PWA_APP_ID,
    name: PWA_APP_NAME,
    short_name: PWA_APP_NAME,
    description: "Minimal notepad built to sit next to the agent tab",
    lang: "en",
    start_url: PWA_START_URL,
    scope: PWA_SCOPE,
    display: "standalone",
    theme_color: PWA_THEME_COLOR,
    background_color: PWA_THEME_COLOR,
    categories: ["productivity", "utilities"],
    // No `orientation`: foldables change aspect ratio on fold / unfold.
    prefer_related_applications: false,
    icons: PWA_ICONS,
  };
}
